// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDsPehsOmbDRuluk5ya1z1y3wHSYWQHQ',
    appId: '1:546282241474:web:48dc1bc75b7f74d4c92a5b',
    messagingSenderId: '546282241474',
    projectId: 'reachout-90f21',
    authDomain: 'reachout-90f21.firebaseapp.com',
    storageBucket: 'reachout-90f21.appspot.com',
    measurementId: 'G-0K46KVNK2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_jnWejtD7v6S1L24A_SKxl76lauGgPE',
    appId: '1:546282241474:android:1d5c317e16897027c92a5b',
    messagingSenderId: '546282241474',
    projectId: 'reachout-90f21',
    storageBucket: 'reachout-90f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9SGHTmmJL5CH_9tspacsWzqJ8jmcgtcI',
    appId: '1:546282241474:ios:c44f8ef993300550c92a5b',
    messagingSenderId: '546282241474',
    projectId: 'reachout-90f21',
    storageBucket: 'reachout-90f21.appspot.com',
    iosBundleId: 'com.example.registrationLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9SGHTmmJL5CH_9tspacsWzqJ8jmcgtcI',
    appId: '1:546282241474:ios:8bea62866f755c33c92a5b',
    messagingSenderId: '546282241474',
    projectId: 'reachout-90f21',
    storageBucket: 'reachout-90f21.appspot.com',
    iosBundleId: 'com.example.registrationLogin.RunnerTests',
  );
}
